apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
  namespace: airflow-cluster
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"] #<<--- เพิ่ม configmaps
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs: ["create", "get", "delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create", "get", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"] #<<--- เพิ่ม PVC
  verbs: ["*"]
- apiGroups: [""]
  resources: ["sparkapplications"]
  verbs: ["*"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
  namespace: airflow-cluster
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: spark-operator
roleRef:
  kind: ClusterRole
  name: airflow-spark-role
  apiGroup: rbac.authorization.k8s.io
